import './globals.css'
import { Inter } from 'next/font/google';
import { ThemeProvider } from "./theme-provider";
import { ThemeContextProvider } from './context/theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Copa Tomada',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        className={`${inter.className} bg-slate-50 dark:bg-[#0d1117]`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeContextProvider>
            {children}
          </ThemeContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

